dist: trusty
language: c
addons:
  apt:
    packages:
    - curl
    - wget
    - unzip
    - rsync
    - oracle-java8-installer
    - oracle-java8-set-default
cache:
  directories:
    - build/helpers
before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./clean.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh
after_success:
  - cd $TRAVIS_BUILD_DIR
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh; fi'


