dist: trusty
language: c
addons:
  apt:
    packages:
    - unzip
    - oracle-java8-installer
    - oracle-java8-set-default
cache:
  directories:
    - build/helpers
before_install: clean.sh
script: build.sh
after_success: deploy.sh
