dist: trusty
language: c
addons:
  apt:
    packages:
    - wget
    - unzip
    - rsync
    - oracle-java8-installer
    - oracle-java8-set-default
cache:
  directories:
    - build/helpers
before_install:
  - cd $TRAVIS_BUILD_DIR
before_script:
  - ./clean.sh
script:
  - ./build.sh
after_success:
  - ./deploy.sh

