dist: trusty
language: c
addons:
  apt:
    packages:
    - unzip
    - oracle-java8-installer
    - oracle-java8-set-default
directories:
  - $HOME/helpers
before_install:
  - mkdir -p $HOME/helpers && wget -nc -O $HOME/helpers/jbake.zip http://hash.to/5HQ && unzip -d $HOME/helpers/jbake $HOME/helpers/jbake
script: $HOME/helpers/jbake -b
