dist: trusty
language: c
addons:
  apt:
    packages:
    - unzip
    - oracle-java8-installer
    - oracle-java8-set-default
directories:
  - $HOME/helpers
before_install:
  - mkdir -p $HOME/helpers && wget -nc -O $HOME/helpers/jbake-2.5.0.zip http://hash.to/5HQ && unzip -d $HOME/helpers/jbake-2.5.0 $HOME/helpers/jbake-2.5.0.zip
script: $HOME/helpers/jbake-2.5.0/bin/jbake -b
