dist: trusty
language: c
addons:
  apt:
    packages:
    - wget
    - unzip
    - rsync
    - oracle-java8-installer
    - oracle-java8-set-default
cache:
  directories:
    - build/helpers
before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./clean.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - ./build.sh
deploy:
  provider: script
  script:
    - ./deploy.sh

