dist: trusty
language: c
addons:
  apt:
    packages:
    - wget
    - unzip
    - rsync
    - oracle-java8-installer
    - oracle-java8-set-default
cache:
  directories:
    - build/helpers
script:
  - clean.sh
  - build.sh
after_success:
  - deploy.sh

